#!/bin/bash

# Usage: push.sh <source_repo_url> <target_repo_url> <branch>
# Requires: GITHUB_SHA environment variable
# Creates a feature branch in target repo with clean code (no configs) from source main branch

set -euo pipefail

if [ $# -lt 3 ]; then
  echo "Usage: $0 <source_repo_url> <target_repo_url> <branch>"
  echo "Requires: GITHUB_SHA environment variable"
  exit 1
fi

SOURCE_REPO=$1
TARGET_REPO=$2
BRANCH=$3
TARGET_USERNAME="${TARGET_USERNAME:-superdesk_support@superdesk.solutions}"

# Get commit SHA from environment
if [ -z "${GITHUB_SHA:-}" ]; then
  echo "ERROR: GITHUB_SHA environment variable is not set."
  exit 1
fi

# Get short commit ID for branch name
SHORT_COMMIT=$(echo "$GITHUB_SHA" | cut -c1-7)
FEATURE_BRANCH="sync-${SHORT_COMMIT}"

echo "==> Starting push process..."
echo "    Source repo: $SOURCE_REPO"
echo "    Target repo: $TARGET_REPO"
echo "    Base branch: $BRANCH"
echo "    Feature branch: $FEATURE_BRANCH"
echo ""

# ── Credentials ────────────────────────────────────────────────────────────────
if [ -z "${CLIENT_PAT:-}" ]; then
  echo "ERROR: CLIENT_PAT environment variable is not set."
  exit 1
fi

git config --global credential.helper store
git config --global user.email "${GIT_USER_EMAIL:-ci@superdesk.solutions}"
git config --global user.name "${GIT_USER_NAME:-CI Bot}"

TARGET_HOST=$(echo "$TARGET_REPO" | awk -F/ '{print $3}')
ENCODED_USER=${TARGET_USERNAME//@/%40}
echo "https://${ENCODED_USER}:${CLIENT_PAT}@${TARGET_HOST}" > ~/.git-credentials
chmod 600 ~/.git-credentials

# ── Cleanup trap ──────────────────────────────────────────────────────────────
WORKDIR=$(mktemp -d)
trap 'rm -rf "$WORKDIR"' EXIT

# ── Clone source repo and get main branch commit ─────────────────────────────
echo "==> Cloning source repo..."
git clone "$SOURCE_REPO" "$WORKDIR/source"
cd "$WORKDIR/source"

# Fetch and checkout the latest main branch
echo "==> Fetching latest main branch..."
git fetch origin "$BRANCH"

SOURCE_COMMIT=$(git rev-parse origin/$BRANCH)
echo "==> Source main branch commit (origin/$BRANCH): $SOURCE_COMMIT"

# Checkout the specific commit from main
git checkout "$SOURCE_COMMIT"

# ── Remove config files ────────────────────────────────────────────────────────
echo "==> Removing config files..."
rm -rf .github CODEOWNERS .gitattributes .gitignore validate.sh push.sh 2>/dev/null || true

echo "==> Files after config removal:"
find . -type f -not -path './.git/*' | head -20
echo "..."

# ── Clone target repo ──────────────────────────────────────────────────────────
AUTH_TARGET_REPO="https://${ENCODED_USER}:${CLIENT_PAT}@${TARGET_REPO#https://}"

# Debug: show masked URL
MASKED_URL=$(echo "$AUTH_TARGET_REPO" | sed 's/:.*@/:***@/')
echo "==> Target repo URL (masked): $MASKED_URL"

echo "==> Cloning target repo..."
git clone --branch "$BRANCH" "$AUTH_TARGET_REPO" "$WORKDIR/target"
cd "$WORKDIR/target"

# Set the origin remote to use authenticated URL for push
echo "==> Setting origin remote URL..."
git remote set-url origin "$AUTH_TARGET_REPO"

# Verify it was set correctly
VERIFY_URL=$(git remote get-url origin | sed 's/:.*@/:***@/')
echo "==> Verified origin URL (masked): $VERIFY_URL"

TARGET_COMMIT=$(git rev-parse HEAD)
echo "==> Target branch commit: $TARGET_COMMIT"

# ── Create feature branch ──────────────────────────────────────────────────────
echo "==> Creating feature branch: $FEATURE_BRANCH"
git checkout -b "$FEATURE_BRANCH"

# ── Copy clean code from source to target ──────────────────────────────────────
echo "==> Copying clean code from source to target..."

# Remove all files except .git directory
find . -mindepth 1 -maxdepth 1 -not -name '.git' -exec rm -rf {} +

# Copy all files from source (which has configs already removed)
cp -r "$WORKDIR/source/." . 2>/dev/null || true

# Remove .git from copied files (we don't want source's git history)
rm -rf .git.bak 2>/dev/null || true

# Restore target's .git
# (it's already there, we just cleaned everything else)

echo "==> Files in feature branch:"
find . -type f -not -path './.git/*' | head -20
echo "..."

# ── Stage all changes ──────────────────────────────────────────────────────────
git add -A

# Check if there are changes to commit
if git diff --cached --quiet; then
  echo ""
  echo "⚠️  No changes to push - codebase already in sync"
  exit 0
fi

# ── Commit and push ────────────────────────────────────────────────────────────
echo "==> Committing changes..."
COMMIT_MSG="Sync code from source (commit: $SHORT_COMMIT)

Source commit: $SOURCE_COMMIT
Configs removed: .github/, CODEOWNERS, .gitattributes, .gitignore, validate.sh, push.sh
Auto-generated by CI/CD pipeline"

git commit -m "$COMMIT_MSG"

echo "==> Verifying git remote configuration..."
git remote -v

echo "==> Pushing feature branch to target repo..."
# Use -v for verbose output to debug
git push -v origin "$FEATURE_BRANCH" 2>&1 || {
  echo ""
  echo "ERROR: Push failed. Attempting direct push with full URL..."
  git push -v "$AUTH_TARGET_REPO" "HEAD:refs/heads/$FEATURE_BRANCH"
}

echo ""
echo "✅ Push complete!"
echo "   Feature branch created: $FEATURE_BRANCH"
echo "   Source commit: $SOURCE_COMMIT"
echo "   Target repo: $TARGET_REPO"
echo ""
echo "   Next steps:"
echo "   1. Review the changes in the feature branch"
echo "   2. Create a merge request in the target repo"
echo "   3. Merge $FEATURE_BRANCH -> $BRANCH"